In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Food Details Dataset

In [3]:
df = pd.read_csv(r'C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\external\all_food_details.csv', delimiter = '|')

df.head(5)

,FOOD_CODE,Name,Unnamed: 2,Latin Name,From,Group,Type,Description
0,AP001,Rice,NaN,NaN,NaN,Cereals,Processed/Products,NaN
1,AP002,"Rice, steamed",NaN,NaN,NaN,Cereals,Processed/Products,NaN
2,AP003,"Rice, tapai",NaN,NaN,NaN,Cereals,Processed/Products,NaN
3,AP004,"Rice, flour, raw",NaN,NaN,NaN,Cereals,Processed/Products,NaN
4,AP005,Red rice,NaN,NaN,NaN,Cereals,Processed/Products,NaN

In [4]:
df.tail(5)

,FOOD_CODE,Name,Unnamed: 2,Latin Name,From,Group,Type,Description
1141,NR021,Kluwek,NaN,NaN,NaN,Herbs and Spices,Raw,NaN
1142,NR022,"Turmeric, fresh",NaN,NaN,NaN,Herbs and Spices,Raw,NaN
1143,NR023,"Pepper, dried",NaN,NaN,NaN,Herbs and Spices,Raw,NaN
1144,NR024,"Nutmeg, seed, dried",NaN,NaN,NaN,Herbs and Spices,Raw,NaN
1145,PR001,"Young coconut, water, fresh",NaN,NaN,NaN,Non-Alcoholic Beverages,Raw,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FOOD_CODE    1146 non-null   object
 1   Name         1146 non-null   object
 2   Unnamed: 2   0 non-null      float64
 3   Latin Name   0 non-null      float64
 4   From         0 non-null      float64
 5   Group        1146 non-null   object
 6   Type         1146 non-null   object
 7   Description  0 non-null      float64
dtypes: float64(4), object(4)
memory usage: 71.8+ KB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

FOOD_CODE         0
Name              0
Unnamed: 2     1146
Latin Name     1146
From           1146
Group             0
Type              0
Description    1146
dtype: int64

# Food Nutrition Dataset

In [8]:
df = pd.read_csv(r'C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\external\all_food_nutritions.csv', delimiter = '|')

df.head(20)

   FOOD_CODE       Nutrient/Ingridient Value (per 100gr)
0      AP001               Air (Water)            56.7 g
1      AP001           Energi (Energy)           180 Kal
2      AP001         Protein (Protein)             3.0 g
3      AP001               Lemak (Fat)             0.3 g
4      AP001         Karbohidrat (CHO)            39.8 g
5      AP001             Serat (Fibre)             0.2 g
6      AP001                 Abu (ASH)             0.2 g
7      AP001              Kalsium (Ca)             25 mg
8      AP001                Fosfor (P)             27 mg
9      AP001                 Besi (Fe)            0.4 mg
10     AP001              Natrium (Na)              1 mg
11     AP001                Kalium (K)           38.0 mg
12     AP001              Tembaga (Cu)           0.10 mg
13     AP001                 Seng (Zn)            0.6 mg
14     AP001          Retinol (Vit. A)             0 mcg
15     AP001  Beta-Karoten (Carotenes)             0 mcg
16     AP001         Thiamin (Vit. B1)           0.05 mg
17     AP001      Riboflavin (Vit. B2)           0.10 mg
18     AP001           Niasin (Niacin)            2.6 mg
19     AP001        Vitamin C (Vit. C)              0 mg

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19712 entries, 0 to 19711
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   FOOD_CODE            19712 non-null  object
 1   Nutrient/Ingridient  19712 non-null  object
 2   Value (per 100gr)    19712 non-null  object
dtypes: object(3)
memory usage: 462.1+ KB

# Food Photos Dataset

In [10]:
df = pd.read_csv(r'C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\external\all_food_photos.csv', delimiter = '|')

df.head(5)

  Food Code                                                 Photo URL
0     AP001  https://www.panganku.org/assets/files/makanan/no_img.jpg
1     AP002  https://www.panganku.org/assets/files/makanan/no_img.jpg
2     AP003  https://www.panganku.org/assets/files/makanan/no_img.jpg
3     AP004  https://www.panganku.org/assets/files/makanan/no_img.jpg
4     AP005  https://www.panganku.org/assets/files/makanan/no_img.jpg

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Food Code  1146 non-null   object
 1   Photo URL  1146 non-null   object
dtypes: object(2)
memory usage: 18.0+ KB

# Dataset Merge (Food Details Dataset & Food Nutrition Dataset)

In [12]:
df = pd.read_csv(r"C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\interim\merged_food_data.csv", delimiter = '|')

df.head(5)

,FOOD_CODE,Nutrient/Ingridient,Value (per 100gr),Name,Group,Type
0,AP001,Air (Water),56.7 g,Rice,Cereals,Processed/Products
1,AP001,Energi (Energy),180 Kal,Rice,Cereals,Processed/Products
2,AP001,Protein (Protein),3.0 g,Rice,Cereals,Processed/Products
3,AP001,Lemak (Fat),0.3 g,Rice,Cereals,Processed/Products
4,AP001,Karbohidrat (CHO),39.8 g,Rice,Cereals,Processed/Products

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19712 entries, 0 to 19711
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   FOOD_CODE            19712 non-null  object
 1   Nutrient/Ingridient  19712 non-null  object
 2   Value (per 100gr)    19712 non-null  object
 3   Name                 19712 non-null  object
 4   Group                19712 non-null  object
 5   Type                 19712 non-null  object
dtypes: object(6)
memory usage: 924.1+ KB

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["Nutrient/Ingridient"].value_counts()

Nutrient/Ingridient
Energi (Energy)             1144
Karbohidrat (CHO)           1144
Abu (ASH)                   1144
Lemak (Fat)                 1143
Protein (Protein)           1143
Air (Water)                 1142
Kalsium (Ca)                1105
Fosfor (P)                  1105
Besi (Fe)                   1102
Thiamin (Vit. B1)           1057
Serat (Fibre)                924
Natrium (Na)                 863
Vitamin C (Vit. C)           856
Kalium (K)                   822
Niasin (Niacin)              806
Seng (Zn)                    798
Riboflavin (Vit. B2)         795
Tembaga (Cu)                 794
Beta-Karoten (Carotenes)     678
Karoten Total (Re)           607
Retinol (Vit. A)             540
Name: count, dtype: int64

In [16]:
df.isnull().sum()

FOOD_CODE              0
Nutrient/Ingridient    0
Value (per 100gr)      0
Name                   0
Group                  0
Type                   0
dtype: int64

# Dataset Pivot

In [17]:
df = pd.read_csv(r"C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\interim\pivoted_food_data.csv", delimiter = '|')

df.head(5)

,FOOD_CODE,Name,Group,Type,Abu (ASH),Air (Water),Besi (Fe),Beta-Karoten (Carotenes),Energi (Energy),Fosfor (P),Kalium (K),Kalsium (Ca),Karbohidrat (CHO),Karoten Total (Re),Lemak (Fat),Natrium (Na),Niasin (Niacin),Protein (Protein),Retinol (Vit. A),Riboflavin (Vit. B2),Seng (Zn),Serat (Fibre),Tembaga (Cu),Thiamin (Vit. B1),Vitamin C (Vit. C)
0,AP001,Rice,Cereals,Processed/Products,0.2 g,56.7 g,0.4 mg,0 mcg,180 Kal,27 mg,38.0 mg,25 mg,39.8 g,0,0.3 g,1 mg,2.6 mg,3.0 g,0 mcg,0.10 mg,0.6 mg,0.2 g,0.10 mg,0.05 mg,0 mg
1,AP002,"Rice, steamed",Cereals,Processed/Products,0.2 g,71.0 g,0.4 mg,0 mcg,120 Kal,7 mg,23.9 mg,3 mg,26.0 g,0,0.4 g,0 mg,1.4 mg,2.4 g,0,0.00 mg,0.4 mg,0.5 g,0.10 mg,0.10 mg,0 mg
2,AP003,"Rice, tapai",Cereals,Processed/Products,0.1 g,75.5 g,0.0 mg,0 mcg,99 Kal,19 mg,2.0 mg,4 mg,22.4 g,0 mcg,0.3 g,26 mg,0.0 mg,1.7 g,0 mcg,0.00 mg,0.5 mg,0.0 g,0.10 mg,0.00 mg,0 mg
3,AP004,"Rice, flour, raw",Cereals,Processed/Products,0.5 g,12.0 g,0.8 mg,0 mcg,353 Kal,140 mg,241.0 mg,5 mg,80.0 g,0 mcg,0.5 g,5 mg,1.2 mg,7.0 g,0 mcg,0.10 mg,0.8 mg,2.4 g,0.10 mg,0.12 mg,0 mg
4,AP005,Red rice,Cereals,Processed/Products,0.3 g,64.0 g,0.8 mg,0 mcg,149 Kal,63 mg,91.4 mg,6 mg,32.5 g,0 mcg,0.4 g,5 mg,1.6 mg,2.8 g,0 mcg,0.00 mg,0.9 mg,0.3 g,0.20 mg,0.06 mg,0 mg

In [18]:
df.tail(5)

,FOOD_CODE,Name,Group,Type,Abu (ASH),Air (Water),Besi (Fe),Beta-Karoten (Carotenes),Energi (Energy),Fosfor (P),Kalium (K),Kalsium (Ca),Karbohidrat (CHO),Karoten Total (Re),Lemak (Fat),Natrium (Na),Niasin (Niacin),Protein (Protein),Retinol (Vit. A),Riboflavin (Vit. B2),Seng (Zn),Serat (Fibre),Tembaga (Cu),Thiamin (Vit. B1),Vitamin C (Vit. C)
1139,NR020,"Coriander, dried",Herbs and Spices,Raw,4.4 g,11.2 g,17.9 mg,75 mcg,418 Kal,370 mg,"1,787.0 mg",630 mg,54.2 g,"1,570 mcg",16.1 g,91 mg,1.8 mg,14.1 g,0,0.35 mg,4.6 mg,12.3 g,0.95 mg,0.20 mg,0 mg
1140,NR021,Kluwek,Herbs and Spices,Raw,1.5 g,51.0 g,2.0 mg,0,310 Kal,100 mg,0,40 mg,13.5 g,0 mcg,24.0 g,0,0,10.0 g,0,0,0,0,0,0.15 mg,30 mg
1141,NR022,"Turmeric, fresh",Herbs and Spices,Raw,1.3 g,84.9 g,3.3 mg,12 mcg,69 Kal,78 mg,406.7 mg,24 mg,9.1 g,0,2.7 g,6 mg,0.4 mg,2.0 g,0,0.02 mg,0.4 mg,0.6 g,0.05 mg,0.03 mg,1 mg
1142,NR023,"Pepper, dried",Herbs and Spices,Raw,4.4 g,12.9 g,16.4 mg,0 mcg,365 Kal,200 mg,99.7 mg,460 mg,64.4 g,0,6.8 g,4 mg,2.5 mg,11.5 g,0,0.10 mg,1.1 mg,1.0 g,0.89 mg,0.20 mg,0
1143,NR024,"Nutmeg, seed, dried",Herbs and Spices,Raw,1.7 g,14.3 g,4.6 mg,7 mcg,518 Kal,240 mg,78.7 mg,120 mg,40.1 g,0,36.4 g,2 mg,0.5 mg,7.5 g,0,0.02 mg,2.0 mg,3.5 g,0.94 mg,0.20 mg,0 mg

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   FOOD_CODE                 1144 non-null   object
 1   Name                      1144 non-null   object
 2   Group                     1144 non-null   object
 3   Type                      1144 non-null   object
 4   Abu (ASH)                 1144 non-null   object
 5   Air (Water)               1144 non-null   object
 6   Besi (Fe)                 1144 non-null   object
 7   Beta-Karoten (Carotenes)  1144 non-null   object
 8   Energi (Energy)           1144 non-null   object
 9   Fosfor (P)                1144 non-null   object
 10  Kalium (K)                1144 non-null   object
 11  Kalsium (Ca)              1144 non-null   object
 12  Karbohidrat (CHO)         1144 non-null   object
 13  Karoten Total (Re)        1144 non-null   object
 14  Lemak (Fat)               1144 non-null   object
 15  Natrium (Na)              1144 non-null   object
 16  Niasin (Niacin)           1144 non-null   object
 17  Protein (Protein)         1144 non-null   object
 18  Retinol (Vit. A)          1144 non-null   object
 19  Riboflavin (Vit. B2)      1144 non-null   object
 20  Seng (Zn)                 1144 non-null   object
 21  Serat (Fibre)             1144 non-null   object
 22  Tembaga (Cu)              1144 non-null   object
 23  Thiamin (Vit. B1)         1144 non-null   object
 24  Vitamin C (Vit. C)        1144 non-null   object
dtypes: object(25)
memory usage: 223.6+ KB

# Data Normalization

In [21]:
df = pd.read_csv(r"C:\Intrenship\Torhe Indonesia\Food Nutrition Detection\data\interim\normalization_data.csv", delimiter = '|')

df.head(5)

,FOOD_CODE,Name,Group,Type,Abu,Air,Besi,Beta-Karoten,Energi,Fosfor,Kalium,Kalsium,Karbohidrat,Karoten Total,Lemak,Natrium,Niasin,Protein,Retinol,Riboflavin,Seng,Serat,Tembaga,Thiamin,Vitamin C
0,AP001,Rice,Cereals,Processed/Products,0.2 g,56.7 g,0.4 mg,0 mcg,180,27 mg,38.0 mg,25 mg,39.8 g,0 mcg,0.3 g,1 mg,2.6 mg,3.0 g,0 mcg,0.10 mg,0.6 mg,0.2 g,0.10 mg,0.05 mg,0 mg
1,AP002,"Rice, steamed",Cereals,Processed/Products,0.2 g,71.0 g,0.4 mg,0 mcg,120,7 mg,23.9 mg,3 mg,26.0 g,0 mcg,0.4 g,0 mg,1.4 mg,2.4 g,0 mcg,0.00 mg,0.4 mg,0.5 g,0.10 mg,0.10 mg,0 mg
2,AP003,"Rice, tapai",Cereals,Processed/Products,0.1 g,75.5 g,0.0 mg,0 mcg,99,19 mg,2.0 mg,4 mg,22.4 g,0 mcg,0.3 g,26 mg,0.0 mg,1.7 g,0 mcg,0.00 mg,0.5 mg,0.0 g,0.10 mg,0.00 mg,0 mg
3,AP004,"Rice, flour, raw",Cereals,Processed/Products,0.5 g,12.0 g,0.8 mg,0 mcg,353,140 mg,241.0 mg,5 mg,80.0 g,0 mcg,0.5 g,5 mg,1.2 mg,7.0 g,0 mcg,0.10 mg,0.8 mg,2.4 g,0.10 mg,0.12 mg,0 mg
4,AP005,Red rice,Cereals,Processed/Products,0.3 g,64.0 g,0.8 mg,0 mcg,149,63 mg,91.4 mg,6 mg,32.5 g,0 mcg,0.4 g,5 mg,1.6 mg,2.8 g,0 mcg,0.00 mg,0.9 mg,0.3 g,0.20 mg,0.06 mg,0 mg